name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Install SQLite and build spellfix extension
        run: |
          mkdir extensions
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev build-essential curl
          curl -L https://raw.githubusercontent.com/sqlite/sqlite/version-3.46.0/ext/misc/spellfix.c -o spellfix.c
          gcc -shared -fPIC -I/usr/include -o extensions/spellfix.so spellfix.c -lsqlite3
          rm spellfix.c

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
